// CONFIGURACIONES DE LIGAS Y URL DE LA API
const WEBAPP_URL = "https://script.google.com/macros/s/AKfycbxP7qj4cs766lujFDKE6bmXop22qZlwwterRySHeMeZjeIGydeO7_uSmPml1zP9a_3Byw/exec";

// Mapeos de códigos de liga a nombres legibles
const leagueNames = {
 "esp.1": "España_LaLiga",
   // "esp.2": "España_Segunda",
    "eng.1": "Inglaterra_PremierLeague",
    "eng.2": "Inglaterra_Championship",
    "ger.1": "Alemania_Bundesliga",
  //  "ger.2": "Alemania_Bundesliga2",
     "ita.1": "Italia_SerieA",
    "fra.1": "Francia_Ligue1",
    "ned.1": "PaísesBajos_Eredivisie",
    "ned.2": "PaísesBajos_EersteDivisie",
    //"por.1": "Portugal_LigaPortugal",
    "mex.1": "México_LigaMX",
   // "mex.2": "México_ExpansionMX",
    "usa.1": "EstadosUnidos_MLS",
    "bra.1": "Brasil_Brasileirao",
    "arg.1": "Argentina_LigaProfesional",
    "gua.1": "Guatemala_LigaNacional",
    //"crc.1": "CostaRica_LigaPromerica",
    //"hon.1": "Honduras_LigaNacional",
    //"slv.1": "ElSalvador_LigaPrimeraDivision",
    "ksa.1": "Arabia_Saudi_ProLeague",
    "tur.1": "Turquia_SuperLig",
    "chn.1": "Superliga China",
    "uefa.champions": "UEFA_Champions_League",
    //"uefa.wchampions": "UEFA_Champions_League_Femenina",
    //"uefa.europa": "UEFA_Europa_League",
    //"uefa.europa.conf": "UEFA_Conference_League",
    //"fifa.worldq.conmebol": "Eliminatorias_CONMEBOL",
    //"fifa.worldq.concacaf": "Eliminatorias_CONCACAF",
    //"fifa.worldq.uefa": "Eliminatorias_UEFA"
};

// Mapeos de códigos de liga a nombres de hoja de cálculo
const leagueCodeToName = {
  "esp.1": "España_LaLiga",
   // "esp.2": "España_Segunda",
    "eng.1": "Inglaterra_PremierLeague",
    "eng.2": "Inglaterra_Championship",
    "ger.1": "Alemania_Bundesliga",
  //  "ger.2": "Alemania_Bundesliga2",
     "ita.1": "Italia_SerieA",
    "fra.1": "Francia_Ligue1",
    "ned.1": "PaísesBajos_Eredivisie",
    "ned.2": "PaísesBajos_EersteDivisie",
    //"por.1": "Portugal_LigaPortugal",
    "mex.1": "México_LigaMX",
   // "mex.2": "México_ExpansionMX",
    "usa.1": "EstadosUnidos_MLS",
    "bra.1": "Brasil_Brasileirao",
    "arg.1": "Argentina_LigaProfesional",
    "gua.1": "Guatemala_LigaNacional",
    //"crc.1": "CostaRica_LigaPromerica",
    //"hon.1": "Honduras_LigaNacional",
    //"slv.1": "ElSalvador_LigaPrimeraDivision",
    "ksa.1": "Arabia_Saudi_ProLeague",
    "tur.1": "Turquia_SuperLig",
    "chn.1": "Superliga China",
    "uefa.champions": "UEFA_Champions_League",
    //"uefa.wchampions": "UEFA_Champions_League_Femenina",
    //"uefa.europa": "UEFA_Europa_League",
    //"uefa.europa.conf": "UEFA_Conference_League",
    //"fifa.worldq.conmebol": "Eliminatorias_CONMEBOL",
    //"fifa.worldq.concacaf": "Eliminatorias_CONCACAF",
    //"fifa.worldq.uefa": "Eliminatorias_UEFA"
};

// Mapeos de regiones
const leagueRegions = {
    "esp.1": "Europa",
    "esp.2": "Europa",
    "eng.1": "Europa",
    "eng.2": "Europa",
    "ita.1": "Europa",
    "ger.1": "Europa",
    "fra.1": "Europa",
    "ned.1": "Europa",
    "ned.2": "Europa",
    "por.1": "Europa",
    "tur.1": "Europa",
    "ger.2": "Europa",
    "arg.1": "Sudamérica",
    "bra.1": "Sudamérica",
    "mex.1": "Norteamérica",
    "mex.2": "Norteamérica",
    "usa.1": "Norteamérica",
    "gua.1": "Centroamérica",
    "crc.1": "Centroamérica",
    "hon.1": "Centroamérica",
    "slv.1": "Centroamérica",
    "ksa.1": "Asia",
    "chn.1": "Asia",
    "conmebol.sudamericana": "Copas Internacionales",
    "conmebol.libertadores": "Copas Internacionales",
    "uefa.champions": "Copas Internacionales",
    "uefa.wchampions": "Copas Internacionales",
    "uefa.europa": "Copas Internacionales",
    "uefa.europa.conf": "Copas Internacionales",
    "fifa.worldq.conmebol": "Eliminatorias Mundiales",
    "fifa.worldq.concacaf": "Eliminatorias Mundiales",
    "fifa.worldq.uefa": "Eliminatorias Mundiales"
};
